name: Backend CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          cat > .env << EOL
          PORT=3001
          DATABASE_URL=postgresql://sei:${{ secrets.DB_PASSWORD }}@37.27.247.208:5432/sei_institute?schema=public
          CLIENT_ENDPOINT=${{ secrets.CLIENT_ENDPOINT }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          ACCESS_TOKEN_EXPIRES=${{ secrets.ACCESS_TOKEN_EXPIRES }}
          REFRESH_TOKEN_EXPIRES=${{ secrets.REFRESH_TOKEN_EXPIRES }}
          NODE_ENV=production
          HUGGING_FACE_KEY=${{ secrets.HUGGING_FACE_KEY }}
          API_URL=${{ secrets.API_URL }}
          EOL

      - name: Build
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r build deploy/
          cp -r prisma deploy/
          mkdir -p deploy/uploads
          mkdir -p deploy/uploads/images
          cp package.json deploy/
          cp package-lock.json deploy/
          cp .env deploy/
          tar -czf backend-deploy.tar.gz -C deploy .

      - name: Deploy to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: 'backend-deploy.tar.gz'
          target: '/tmp'

      - name: Extract and setup on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Kill any existing processes on port 3001
            if lsof -i :3001 -t; then
              kill -9 $(lsof -i :3001 -t) || true
            fi

            # Create directory if not exists
            mkdir -p /var/www/sei-institute/backend

            # Backup the current deployment before extracting
            if [ -d "/var/www/sei-institute/backend/build" ]; then
              timestamp=$(date +%Y%m%d%H%M%S)
              mkdir -p /var/www/sei-institute/backups
              tar -czf /var/www/sei-institute/backups/backend-backup-$timestamp.tar.gz -C /var/www/sei-institute/backend .
            fi

            # Extract deployment package
            tar -xzf /tmp/backend-deploy.tar.gz -C /var/www/sei-institute/backend

            # Ensure uploads directory exists with proper permissions
            mkdir -p /var/www/sei-institute/backend/uploads
            mkdir -p /var/www/sei-institute/backend/uploads/images
            chmod -R 755 /var/www/sei-institute/backend/uploads

            # Install production dependencies
            cd /var/www/sei-institute/backend
            npm ci --production

            # Run database migrations (without recreating the database)
            # This applies schema changes but doesn't drop existing data
            npx prisma migrate deploy

            # Delete any existing backend app in PM2
            pm2 delete backend-app || true

            # Start a fresh instance
            pm2 start build/server.js --name backend-app
            pm2 save

            # Verify server is running
            echo "Verifying backend server is running..."
            if lsof -i :3001 | grep LISTEN; then
              echo "Backend server is running successfully on port 3001"
            else
              echo "WARNING: Backend server failed to start on port 3001"
            fi

            # Cleanup
            rm /tmp/backend-deploy.tar.gz
