name: Deploy Backend

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate .env file from secrets
        run: |
          # Create .env file from secrets
          echo "DATABASE_URL=postgresql://sei_user:sei@37.27.247.208:5432/sei_institute?schema=public" > .env.production
          echo "JWT_SECRET=${{ secrets.BACKEND_JWT_SECRET || 'your-super-secret-jwt-key' }}" >> .env.production
          echo "PORT=3333" >> .env.production
          echo "NODE_ENV=production" >> .env.production
          echo "FRONTEND_URL=https://seiinstitute.com" >> .env.production
          echo "API_URL=https://api.seiinstitute.com" >> .env.production

      - name: Build application
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Setup SSH directory
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to server
        env:
          SERVER_PASSWORD: gkjaRhMActfMatPW7nvd
        run: |
          # Copy built files directly to the server
          sshpass -p "$SERVER_PASSWORD" rsync -avz --delete ./build/ ./package.json ./package-lock.json ./prisma/ ./.env.production root@37.27.247.208:/opt/sei-institute/backend/

          # Restart the PM2 process - ensure necessary build tools are installed
          sshpass -p "$SERVER_PASSWORD" ssh root@37.27.247.208 'cd /opt/sei-institute/backend && npm ci --production --no-optional --omit=dev && npx prisma generate && mv .env.production .env && pm2 restart backend || pm2 start build/index.js --name backend && pm2 save'

      - name: Verify deployment
        env:
          SERVER_PASSWORD: gkjaRhMActfMatPW7nvd
        run: |
          # Check if service is running with PM2
          sshpass -p "$SERVER_PASSWORD" ssh root@37.27.247.208 'pm2 status backend'
