name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: 37.27.247.208
          username: root
          password: gkjaRhMActfMatPW7nvd
          script: |
            set -e
            DEPLOY_DIR="/var/www/sei-institute"

            # Fix ownership of the parent directory
            mkdir -p /var/www
            chown -R root:root /var/www
            echo "Ownership of /var/www fixed:"
            ls -ld /var/www

            # Mark the deployment directory as safe for Git
            git config --global --add safe.directory $DEPLOY_DIR
            echo "Safe directory set: $DEPLOY_DIR"

            # Clone or update repository
            if [ ! -d "$DEPLOY_DIR" ]; then
              echo "Cloning repository to $DEPLOY_DIR..."
              git clone --single-branch --branch main https://github.com/${{ github.repository }}.git $DEPLOY_DIR
            else
              echo "Updating repository in $DEPLOY_DIR..."
              cd $DEPLOY_DIR
              git fetch origin
              git reset --hard origin/main
            fi

            # Debug repository contents
            echo "Checking repository structure..."
            ls -la $DEPLOY_DIR
            echo "Checking backend directory..."
            ls -la $DEPLOY_DIR/backend
            echo "Checking prisma directory..."
            ls -la $DEPLOY_DIR/backend/prisma || echo "Prisma directory not found!"

            # Make sure prisma directory exists
            if [ ! -d "$DEPLOY_DIR/backend/prisma" ]; then
              echo "Creating prisma directory..."
              mkdir -p $DEPLOY_DIR/backend/prisma
            fi

            # Copy schema.prisma if it doesn't exist
            if [ ! -f "$DEPLOY_DIR/backend/prisma/schema.prisma" ]; then
              echo "schema.prisma not found, creating it..."
              # Create a basic schema.prisma file - you may need to adjust this based on your actual schema
              cat > $DEPLOY_DIR/backend/prisma/schema.prisma << 'EOD'
              generator client {
                provider = "prisma-client-js"
              }
              
              datasource db {
                provider = "postgresql"
                url      = env("DATABASE_URL")
              }
              EOD
              
              # Also check if schema exists in node_modules
              if [ -f "$DEPLOY_DIR/backend/node_modules/.prisma/client/schema.prisma" ]; then
                echo "Found schema in node_modules, copying it..."
                cp $DEPLOY_DIR/backend/node_modules/.prisma/client/schema.prisma $DEPLOY_DIR/backend/prisma/schema.prisma
              fi
            fi

            # Navigate to the backend directory
            cd $DEPLOY_DIR/backend
            BACKEND_DIR="$DEPLOY_DIR/backend"

            # Install PostgreSQL if not present
            if ! command -v psql &> /dev/null; then
              apt-get update
              apt-get install -y postgresql postgresql-contrib
              systemctl start postgresql
              systemctl enable postgresql
            fi

            # Use the correct postgres password
            POSTGRES_PASS="mahato"
            export PGPASSWORD=$POSTGRES_PASS

            # Test PostgreSQL connection
            psql -U postgres -h 127.0.0.1 -c "SELECT 1;" || {
              echo "Error: Failed to connect to PostgreSQL with password 'mahato'"
              cat /var/log/postgresql/postgresql-*-main.log | tail -n 20
              exit 1
            }

            # Create database user and database
            echo "Creating sei user and database..."
            psql -U postgres -h 127.0.0.1 -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sei') THEN CREATE USER sei WITH PASSWORD 'sei'; END IF; END \$\$;"
            psql -U postgres -h 127.0.0.1 -c "DROP DATABASE IF EXISTS sei;" || true
            psql -U postgres -h 127.0.0.1 -c "CREATE DATABASE sei OWNER sei;"
            psql -U postgres -h 127.0.0.1 -d sei -c "GRANT ALL PRIVILEGES ON SCHEMA public TO sei;"

            # Set environment variables with hardcoded sei/sei credentials
            cat > $BACKEND_DIR/.env << 'EOD'
            PORT=9000
            DATABASE_URL="postgresql://sei:sei@127.0.0.1:5432/sei?schema=public"
            CLIENT_ENDPOINT="https://seiinstitute.com"
            JWT_SECRET="${{ secrets.JWT_SECRET }}"
            ACCESS_TOKEN_EXPIRES="1d"
            REFRESH_TOKEN_EXPIRES="7d"
            NODE_ENV="production"
            HUGGING_FACE_KEY="${{ secrets.HUGGING_FACE_KEY }}"
            API_URL="https://api.seiinstitute.com"
            EOD

            # Install dependencies
            cd $BACKEND_DIR
            npm ci

            # Ensure Prisma schema is present
            if [ ! -f "$BACKEND_DIR/prisma/schema.prisma" ]; then
              echo "Error: schema.prisma not found in $BACKEND_DIR/prisma/"
              exit 1
            fi

            # Check and display Prisma schema content
            echo "Prisma schema content:"
            cat $BACKEND_DIR/prisma/schema.prisma

            # Run Prisma commands
            npx prisma generate --schema=$BACKEND_DIR/prisma/schema.prisma
            npx prisma migrate deploy --schema=$BACKEND_DIR/prisma/schema.prisma

            # Configure Nginx for API
            cat > /etc/nginx/sites-available/api.seiinstitute.com << 'EOD'
            server {
                listen 80;
                server_name api.seiinstitute.com;

                location / {
                    proxy_pass http://localhost:9000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_cache_bypass $http_upgrade;
                }
            }
            EOD
            ln -sf /etc/nginx/sites-available/api.seiinstitute.com /etc/nginx/sites-enabled/
            nginx -t && systemctl restart nginx

            # Build and start backend with PM2
            cd $BACKEND_DIR
            npm run build
            if [ ! -f "$BACKEND_DIR/build/server.js" ]; then
              echo "Error: build/server.js not found after build"
              ls -la $BACKEND_DIR/build
              exit 1
            fi
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            pm2 delete backend || true
            pm2 start $BACKEND_DIR/build/server.js --name backend
            pm2 save
            pm2 startup systemd -u root --hp /root

            # Install Certbot and configure SSL
            if ! command -v certbot &> /dev/null; then
              apt-get update
              apt-get install -y certbot python3-certbot-nginx
            fi
            certbot --nginx -d api.seiinstitute.com --non-interactive --agree-tos --email your-email@example.com
            nginx -t && systemctl restart nginx

            echo "Backend deployment with SSL completed!"
