name: Deploy SEI Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug directory structure
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp -r build package.json package-lock.json prisma deploy/
          [ -f .env.example ] && cp .env.example deploy/ || echo "No .env.example found, skipping"
          cd deploy
          npm ci --production
          npx prisma generate

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: 37.27.247.208
          username: root
          password: gkjaRhMActfMatPW7nvd
          port: 22
          source: 'deploy/*'
          target: '/tmp/sei-deploy'
          strip_components: 1

      - name: Move files and restart service
        uses: appleboy/ssh-action@master
        with:
          host: 37.27.247.208
          username: root
          password: gkjaRhMActfMatPW7nvd
          port: 22
          script: |
            mkdir -p /var/www/sei-institute/backend
            cp -r /tmp/sei-deploy/* /var/www/sei-institute/backend/
            cd /var/www/sei-institute/backend
            npm ci --production
            npx prisma generate
            # Create .env if it doesn't exist and populate with secrets
            if [ ! -f .env ]; then
              [ -f .env.example ] && cp .env.example .env || echo "" > .env
              echo "PORT=9000" >> .env
              echo "DATABASE_URL=\"postgresql://sei_user:sei@37.27.247.208:5432/sei_institute?schema=public\"" >> .env
              echo "CLIENT_ENDPOINT=\"https://seiinstitute.com\"" >> .env
              echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env
              echo "ACCESS_TOKEN_EXPIRES=\"1d\"" >> .env
              echo "REFRESH_TOKEN_EXPIRES=\"7d\"" >> .env
              echo "NODE_ENV=\"production\"" >> .env
              echo "POSTGRES_HOST_AUTH_METHOD=\"trust\"" >> .env
              echo "HUGGING_FACE_KEY=\"${{ secrets.HUGGING_FACE_KEY }}\"" >> .env
            fi
            npx prisma migrate deploy
            npm run prisma:seed
            pm2 restart sei-backend || pm2 start build/server.js --name sei-backend
            rm -rf /tmp/sei-deploy
