name: Deploy SEI Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build
        working-directory: ./backend
        run: npm run build

      - name: Prepare deployment package
        working-directory: ./backend
        run: |
          mkdir -p deploy
          cp -r build package.json package-lock.json prisma .env.example deploy/
          cd deploy
          # Create a production-only package without dev dependencies
          npm ci --production

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: 'backend/deploy/*'
          target: '/tmp/sei-deploy'
          strip_components: 2

      - name: Move files and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/sei-institute/backend
            cp -r /tmp/sei-deploy/* /var/www/sei-institute/backend/
            cd /var/www/sei-institute/backend

            # Set up environment variables
            if [ ! -f .env ]; then
              cp .env.example .env
              # You should manually update the .env file with real values after the first deployment
            fi

            # Run database migrations
            npx prisma migrate deploy

            # Start or restart the application
            pm2 restart sei-backend || pm2 start build/server.js --name sei-backend

            # Clean up
            rm -rf /tmp/sei-deploy
