name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: 37.27.247.208
          username: root
          password: gkjaRhMActfMatPW7nvd
          script: |
            # Create or update backend repository
            if [ ! -d "/var/www/sei-institute/backend/.git" ]; then
              # First time setup - clone repo
              mkdir -p /var/www/sei-institute/backend
              git clone --single-branch --branch main https://github.com/${{ github.repository }}.git /var/www/sei-institute/backend
              cd /var/www/sei-institute/backend
            else
              # Update existing repo
              cd /var/www/sei-institute/backend
              git fetch origin
              git reset --hard origin/main
            fi

            # Install PostgreSQL if not installed
            if ! command -v psql &> /dev/null; then
              apt-get update
              apt-get install -y postgresql postgresql-contrib
            fi

            # Ensure PostgreSQL is running
            systemctl enable postgresql
            systemctl start postgresql
            sleep 5 # Give PostgreSQL time to start

            # Fix PostgreSQL authentication configuration
            sudo sed -i 's/local\s\+all\s\+postgres\s\+peer/local all postgres md5/g' /etc/postgresql/*/main/pg_hba.conf
            sudo sed -i 's/host\s\+all\s\+all\s\+127.0.0.1\/32\s\+peer/host all all 127.0.0.1\/32 md5/g' /etc/postgresql/*/main/pg_hba.conf
            systemctl restart postgresql
            sleep 5 # Give time for restart

            # Set postgres password
            echo "ALTER USER postgres WITH PASSWORD 'mahato';" | sudo -u postgres psql || true

            # Setup database user and permissions
            sudo -u postgres psql <<EOD
            DO \$\$
            BEGIN
              IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'sei_prod_user') THEN
                ALTER ROLE sei_prod_user WITH PASSWORD 'StrongP@ssw0rd123';
              ELSE
                CREATE USER sei_prod_user WITH PASSWORD 'StrongP@ssw0rd123';
              END IF;
            END
            \$\$;

            SELECT 'CREATE DATABASE sei_institute'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'sei_institute');

            GRANT ALL PRIVILEGES ON DATABASE sei_institute TO sei_prod_user;
            \c sei_institute
            GRANT ALL ON SCHEMA public TO sei_prod_user;
            EOD

            # Set production environment variables in .env file with hardcoded values
            cat > /var/www/sei-institute/backend/.env <<EOD
            PORT=9000
            DATABASE_URL="postgresql://sei_prod_user:StrongP@ssw0rd123@127.0.0.1:5432/sei_institute?schema=public"
            CLIENT_ENDPOINT="https://seiinstitute.com"
            JWT_SECRET="mahatohariomsfadfnasldkjf"
            ACCESS_TOKEN_EXPIRES="1d"
            REFRESH_TOKEN_EXPIRES="7d"
            NODE_ENV="production"
            HUGGING_FACE_KEY="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"
            API_URL="https://api.seiinstitute.com"
            EOD

            # Install dependencies and fix vulnerabilities
            cd /var/www/sei-institute/backend
            npm ci
            npm audit fix || true

            # Run Prisma migrations
            cd /var/www/sei-institute/backend
            npx prisma generate
            npx prisma migrate deploy

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi

            # Start/Restart application using PM2
            cd /var/www/sei-institute/backend
            pm2 describe backend > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              # Restart if already exists
              pm2 restart backend --update-env
            else
              # Start new process
              pm2 start build/server.js --name backend
            fi
            pm2 save

            # Verify deployment
            if [ -d "/var/www/sei-institute/backend/build" ]; then
              echo "Build directory exists, deployment successful"
            else
              echo "ERROR: Build directory does not exist, deployment failed"
              exit 1
            fi
