name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: 37.27.247.208
          username: root
          password: gkjaRhMActfMatPW7nvd
          script: |
            set -e
            DEPLOY_DIR="/var/www/sei-institute/backend"

            # Clone or update repository
            if [ ! -d "$DEPLOY_DIR" ]; then
              mkdir -p $DEPLOY_DIR
              git clone --single-branch --branch main https://github.com/${{ github.repository }}.git $DEPLOY_DIR
            else
              cd $DEPLOY_DIR
              git fetch origin
              git reset --hard origin/main
            fi

            # Install PostgreSQL if not present
            if ! command -v psql &> /dev/null; then
              apt-get update
              apt-get install -y postgresql postgresql-contrib
              systemctl start postgresql
              systemctl enable postgresql
            fi

            # Setup PostgreSQL database and user
            sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sei') THEN CREATE USER sei WITH PASSWORD 'sei'; END IF; END \$\$;"
            sudo -u postgres psql -c "DROP DATABASE IF EXISTS sei;" || true
            sudo -u postgres psql -c "CREATE DATABASE sei OWNER sei;"
            sudo -u postgres psql -d sei -c "GRANT ALL PRIVILEGES ON SCHEMA public TO sei;"

            # Set environment variables
            cat > $DEPLOY_DIR/.env << 'EOD'
            PORT=9000
            DATABASE_URL="postgresql://sei:sei@127.0.0.1:5432/sei?schema=public"
            CLIENT_ENDPOINT="https://seiinstitute.com"
            JWT_SECRET="mahatohariomsfadfnasldkjf"
            ACCESS_TOKEN_EXPIRES="1d"
            REFRESH_TOKEN_EXPIRES="7d"
            NODE_ENV="production"
            HUGGING_FACE_KEY="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"
            API_URL="https://api.seiinstitute.com"
            EOD

            # Install dependencies and run Prisma migrations
            cd $DEPLOY_DIR
            npm ci
            npx prisma generate
            npx prisma migrate deploy

            # Configure Nginx for API (HTTP initially)
            cat > /etc/nginx/sites-available/api.seiinstitute.com << 'EOD'
            server {
                listen 80;
                server_name api.seiinstitute.com;

                location / {
                    proxy_pass http://localhost:9000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_cache_bypass $http_upgrade;
                }
            }
            EOD
            ln -sf /etc/nginx/sites-available/api.seiinstitute.com /etc/nginx/sites-enabled/
            nginx -t && systemctl restart nginx

            # Build and start backend with PM2
            cd $DEPLOY_DIR
            npm run build
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            pm2 delete backend || true
            pm2 start build/server.js --name backend
            pm2 save
            pm2 startup systemd -u root --hp /root

            # Install Certbot and configure SSL for API
            if ! command -v certbot &> /dev/null; then
              apt-get update
              apt-get install -y certbot python3-certbot-nginx
            fi

            # Obtain SSL certificate for API
            certbot --nginx -d api.seiinstitute.com --non-interactive --agree-tos --email your-email@example.com

            # Reload Nginx with SSL config
            nginx -t && systemctl restart nginx

            echo "Backend deployment with SSL completed!"
